version: '3'
services:
  react-app:
    # stdin_open: true
    # tty: true
    # build: .
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_NAME=DockerReactDevelopment
